import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-neutral-50 dark:bg-neutral-800 text-gray-800 dark:text-gray-200`}
        >
          <Header />
          <main className="flex-grow px-4 sm:px-6 lg:px-8 bg-white dark:bg-neutral-900 shadow-md rounded-lg">
            {children}
          </main>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  );
}
